GoPark/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:'car_logs#home'
  get 'car_logs/profile', to:'car_logs#profile'
  get 'car_logs/new', to:'car_logs#new'
  get 'car_logs/show', to:'car_logs#show'
  resources:car_logs
end

GoPark/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

GoPark/app/models/car_log.rb
class CarLog < ActiveRecord::Base
  validates :plate_number, presence:true, length: { minimum:4, maximum: 8}
  validates :time_in, presence:true
  validates :time_out, presence:true
  validates :color, presence:true
  validates :brand, presence:true
  self.table_name = "carlogs"
  # length {minimum: , maximum: ,in: 6..20, is: 6}
end

GoPark/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

GoPark/app/controllers/car_logs_controller.rb
class CarLogsController < ApplicationController
  def new
    @carlogs = CarLog.new
  end

  def create
    @carlogs = CarLog.new(carlogs_params)
    if @carlogs.save
        redirect_to car_log_path(@carlogs), notice: "You have successfully registered!"
    else
        render "new"
    end
  end

  def show
    if CarLog.all.count.zero?
      redirect_to root_path, alert: "There are no registered cars yet!"
    else
      @carlogs = CarLog.last
    end
  end

  private
    def carlogs_params
      params.require(:car_log).permit(:plate_number, :time_in, :time_out, :color, :brand, :created_at, :updated_at)
    end
end

GoPark/app/helpers/application_helper.rb
module ApplicationHelper
end

GoPark/app/views/car_logs/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoPark</title>
    <%= stylesheet_link_tag "park.css" %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans:400,700" rel="stylesheet">
  </head>
  <body>
    <nav class="main-navbar">
       <div class="navigation-wrapper">
         <img  src="/pics/GoPark2.png" alt="" width="60px">
       </div>
       <div class="nav-items">
         <%= link_to "About Creator", car_logs_profile_path, class: 'navbutton' %>
       </div>
   </nav>
    <div class="section-container">
      <!-- <img class="photo-main" src="/pics/GoPark2.png" alt="" width="5%"> -->
      <img class="photo-main" src="/pics/GoPark3.png" alt="" width="50%">
      <span>
        <%= link_to "Create Car Log", car_logs_new_path, class: 'button' %>
        <%= link_to "View Car Log", car_logs_show_path, class: 'button m' %>
      </span>
    </div>
  </body>
</html>

GoPark/app/views/car_logs/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoPark</title>
    <%= stylesheet_link_tag "park.css" %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans:400,700" rel="stylesheet">
  </head>
  <body>
    <nav class="main-navbar">
       <div class="navigation-wrapper">
         <img  src="/pics/GoPark2.png" alt="" width="60px">
       </div>
       <div class="nav-items">
         <%= link_to "Home", root_path, class: 'navbutton' %>
         <%= link_to "About Creator", car_logs_profile_path, class: 'navbutton m' %>
         <%= link_to "View Car Log", car_logs_show_path, class: 'navbutton m' %>
       </div>
   </nav>
    <div class="section-container">
      <div class="error">
        <h1>Create New Car Log</h1>
        <% if @carlogs.errors.any? %>

        <h2>Errors:</h2>
          <% @carlogs.errors.full_messages.each do |msg| (:li) %>
          <%= msg %>
          <% end %>
        <% end %>
      </div>
      <%= form_for @carlogs do |t| %>
        <table>
          <tr>
            <th><%= t.label :plate_number %></th>
            <th><%= t.text_field :plate_number %></th>
          </tr>
          <tr>
            <th><%= t.label :color %></th>
            <th><%= t.select :color, ['Black', 'White', 'Blue', 'Red', 'Silver', 'Yellow'], :prompt => 'Select One' %></th>
          </tr>
          <tr>
            <th><%= t.label :brand %></th>
            <th><%= t.select :brand, ['Toyota', 'Honda', 'BMW', 'Mercedes', 'Ford', 'Ferrari', 'Hyundai', 'Porsche'], :prompt => 'Select One' %></th>
          </tr>
          <tr>
            <th><%= t.label :time_in %></th>
            <th><%= t.time_field :time_in %></th>
          </tr>
          <tr>
            <th><%= t.label :time_out %></th>
            <th><%= t.time_field :time_out %></th>
          </tr>
            <td colspan="2"><%= t.submit 'Submit', class: 'button' =%></td>
          </table>

      <% end %>
    </div>
  </body>
</html>

GoPark/app/views/car_logs/profile.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoPark</title>
    <%= stylesheet_link_tag "park.css" %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans:400,700" rel="stylesheet">
  </head>
  <body>
    <nav class="main-navbar">
       <div class="navigation-wrapper">
         <img  src="/pics/GoPark2.png" alt="" width="60px">
       </div>
       <div class="nav-items">
         <%= link_to "Home", root_path, class: 'navbutton' %>
         <%= link_to "Create Car Log", car_logs_new_path, class: 'navbutton m' %>
       </div>
   </nav>
    <div class="section-container">
      <h1 >Hello, I'm Andii</h1>
      <img class="photo-main" src="/pics/profile.jpg" alt="" width="30%">
      <p>
        I am a 3 BS Management Information Systems student who loves animals and travelling.
      </p>
    </div>
  </body>
</html>

GoPark/app/views/car_logs/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoPark</title>
    <%= stylesheet_link_tag "park.css" %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans:400,700" rel="stylesheet">
  </head>
  <body>
    <nav class="main-navbar">
       <div class="navigation-wrapper">
         <img  src="/pics/GoPark2.png" alt="" width="60px">
       </div>
       <div class="nav-items">
         <%= link_to "Home", root_path, class: 'navbutton' %>
         <%= link_to "About Creator", car_logs_profile_path, class: 'navbutton m' %>
         <%= link_to "Create Car Log", car_logs_new_path, class: 'navbutton m' %>
       </div>
   </nav>
    <div class="section-container">
      <h1>Last CarLogs</h1>
      <table>
        <tr>
          <th>Plate Number:</th>
          <th> <%= @carlogs.plate_number %></th>
        </tr>
        <tr>
          <th>Color:</th>
          <th><%= @carlogs.color %></th>
        </tr>
        <tr>
          <th>Brand:</th>
          <th><%= @carlogs.brand %></th>
        </tr>
        <tr>
          <th>Time-in:</th>
          <th><%= @carlogs.time_in %></th>
        </tr>
        <tr>
          <th>Time-out:</th>
          <th><%= @carlogs.time_out %></th>

        </tr>
        <tr>
          <th>Created at:</th>
          <th><%= Time.now.strftime("%B %e, %Y at %I:%M %p") %></th>
        </tr>
        <tr>
          <th>Updated at:</th>
          <th><%= Time.now.strftime("%B %e, %Y at %I:%M %p") %></th>
          </th>
        </tr>
        </table>

    </div>
  </body>
</html>

GoPark/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoPark</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <div class="section alert-success">
        <% if notice %>
          <%= notice %>
        <% end %>
      </div>
      <div class="section alert-danger">
        <% if alert %>
          <%= alert %>
        <% end %>
      </div>
    </div>




    <%= yield %>
  </body>
</html>